// This file was generated by lezer-generator. You probably shouldn't edit it.
export const Http = 1,
	HttpRequestMethod = 2,
	HttpRequestPath = 3,
	HttpHeaders = 4,
	HttpHeader = 5,
	HttpHeaderName = 6,
	HttpHeaderValue = 7,
	HttpBody = 8;
