// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/orgs/atomic-ehr/repositories
// Any manual changes made to this file may be overwritten.

import type { Narrative } from "../hl7-fhir-r4-core/Narrative";
import type { Resource } from "../hl7-fhir-r4-core/Resource";

export type { Narrative } from "../hl7-fhir-r4-core/Narrative";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/DomainResource
export interface DomainResource extends Resource {
	resourceType: "DomainResource" | "OperationOutcome";

	contained?: Resource[];
	text?: Narrative;
}
