// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
import type { DomainResource } from "../hl7-fhir-r4-core/DomainResource";
import type { HumanName } from "../hl7-fhir-r4-core/HumanName";
import type { Identifier } from "../hl7-fhir-r4-core/Identifier";
import type { Reference } from "../hl7-fhir-r4-core/Reference";

import type { Element } from "../hl7-fhir-r4-core/Element";
export type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
export type { HumanName } from "../hl7-fhir-r4-core/HumanName";
export type { Identifier } from "../hl7-fhir-r4-core/Identifier";
export type { Reference } from "../hl7-fhir-r4-core/Reference";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/Patient (pkg: hl7.fhir.r4.core#4.0.1)
export interface Patient extends DomainResource {
    resourceType: "Patient";

    active?: boolean;
    _active?: Element;
    birthDate?: string;
    _birthDate?: Element;
    deceasedBoolean?: boolean;
    _deceasedBoolean?: Element;
    deceasedDateTime?: string;
    _deceasedDateTime?: Element;
    gender?: ("male" | "female" | "other" | "unknown");
    _gender?: Element;
    generalPractitioner?: Reference<"Organization" | "Practitioner" | "PractitionerRole">[];
    identifier?: Identifier[];
    managingOrganization?: Reference<"Organization">;
    maritalStatus?: CodeableConcept<("A" | "D" | "I" | "L" | "M" | "P" | "S" | "T" | "U" | "W" | "UNK" | string)>;
    multipleBirthBoolean?: boolean;
    _multipleBirthBoolean?: Element;
    multipleBirthInteger?: number;
    _multipleBirthInteger?: Element;
    name?: HumanName[];
}
export const isPatient = (resource: unknown): resource is Patient => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "Patient";
}
