name: React components
on:
  push:
  pull_request:

jobs:
  prepare:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
  lint:
    needs: prepare
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm --filter @health-samurai/react-components run lint:check
  typecheck:
    needs: prepare
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Type check
        run: pnpm --filter @health-samurai/react-components run tsc:check
  build:
    needs: prepare
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm --filter @health-samurai/react-components run build
  build-storybook:
    needs: 
      - prepare
      - lint
      - typecheck
      - build
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build storybook
        run: pnpm --filter @health-samurai/react-components run build-storybook
      - name: Setup Pages
        uses: actions/configure-pages@v4
        if: success() && github.ref == 'refs/heads/master'
      - name: Upload
        uses: actions/upload-pages-artifact@v3
        if: success() && github.ref == 'refs/heads/master'
        with:
          path: packages/react-components/storybook-static
  storybook-deploy-pages:
    if: success() && github.ref == 'refs/heads/master'
    needs: build-storybook

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
